insert into Customer (id, username, password, name) values (1, 'gavin', 'foobar', 'Gavin King')
insert into Customer (id, username, password, name) values (2, 'demo', 'demo', 'Demo User')
insert into Hotel (id, price, name, address, city, state, zip, country) values (1, 120, 'Marriott Courtyard', 'Tower Place, Buckhead', 'Atlanta', 'GA', '30305', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (2, 180, 'Doubletree', 'Tower Place, Buckhead', 'Atlanta', 'GA', '30305', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (3, 450, 'W Hotel', 'Union Square, Manhattan', 'NY', 'NY', '10011', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (4, 450, 'W Hotel', 'Lexington Ave, Manhattan', 'NY', 'NY', '10011', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (5, 250, 'Hotel Rouge', '1315 16th Street NW', 'Washington', 'DC', '20036', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (6, 300, '70 Park Avenue Hotel', '70 Park Avenue', 'NY', 'NY', '10011', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (8, 300, 'Conrad Miami', '1395 Brickell Ave', 'Miami', 'FL', '33131', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (9, 80, 'Sea Horse Inn', '2106 N Clairemont Ave', 'Eau Claire', 'WI', '54703', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (10, 90, 'Super 8 Eau Claire Campus Area', '1151 W Macarthur Ave', 'Eau Claire', 'WI', '54701', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (11, 160, 'Marriott Downtown', '55 Fourth Street', 'San Francisco', 'CA', '94103', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (12, 200, 'Hilton Diagonal Mar', 'Passeig del Taulat 262-264', 'Barcelona', 'Catalunya', '08019', 'Spain')
insert into Hotel (id, price, name, address, city, state, zip, country) values (13, 210, 'Hilton Tel Aviv', 'Independence Park', 'Tel Aviv', '', '63405', 'Israel')
insert into Hotel (id, price, name, address, city, state, zip, country) values (14, 240, 'InterContinental Tokyo Bay', 'Takeshiba Pier', 'Tokyo', '', '105', 'Japan')
insert into Hotel (id, price, name, address, city, state, zip, country) values (15, 130, 'Hotel Beaulac', ' Esplanade L�opold-Robert 2', 'Neuchatel', '', '2000', 'Switzerland')
insert into Hotel (id, price, name, address, city, state, zip, country) values (16, 140, 'Conrad Treasury Place', 'William & George Streets', 'Brisbane', 'QLD', '4001', 'Australia')
insert into Hotel (id, price, name, address, city, state, zip, country) values (17, 230, 'Ritz Carlton', '1228 Sherbrooke St', 'West Montreal', 'Quebec', 'H3G1H6', 'Canada')
insert into Hotel (id, price, name, address, city, state, zip, country) values (18, 460, 'Ritz Carlton', 'Peachtree Rd, Buckhead', 'Atlanta', 'GA', '30326', 'USA')
insert into Hotel (id, price, name, address, city, state, zip, country) values (19, 220, 'Swissotel', '68 Market Street', 'Sydney', 'NSW', '2000', 'Australia')
insert into Hotel (id, price, name, address, city, state, zip, country) values (20, 250, 'Meli� White House', 'Albany Street', 'Regents Park London', '', 'NW13UP', 'Great Britain')
insert into Hotel (id, price, name, address, city, state, zip, country) values (21, 210, 'Hotel Allegro', '171 West Randolph Street', 'Chicago', 'IL', '60601', 'USA')

insert into enum_domain(id, domain_name) values(1, 'gender')
insert into enum_instance(id, instance_name, domain_id) values(101, 'Male', 1)
insert into enum_instance(id, instance_name, domain_id) values(102, 'Female', 1)
insert into enum_instance(id, instance_name, domain_id) values(103, 'Unisex', 1)

insert into enum_domain(id, domain_name) values(2, 'category')
insert into enum_instance(id, instance_name, domain_id) values(201, 'Top', 2)
insert into enum_instance(id, instance_name, domain_id) values(202, 'Pants', 2)

insert into enum_domain(id, domain_name) values(3, 'size')
insert into enum_instance(id, instance_name, domain_id) values(301, 'S', 3)
insert into enum_instance(id, instance_name, domain_id) values(302, 'M', 3)
insert into enum_instance(id, instance_name, domain_id) values(303, 'L', 3)

insert into enum_domain(id, domain_name) values(4, 'color')
insert into enum_instance(id, instance_name, domain_id) values(401, 'Black', 4)
insert into enum_instance(id, instance_name, domain_id) values(402, 'White', 4)
insert into enum_instance(id, instance_name, domain_id) values(403, 'Gray', 4)

insert into label(id, label_name) values(1, 'TestLabel1')

insert into product(id, factory_barcode, factory_code, product_code, product_name, display_name, gender_instance_id, summary, description, wholesale_price, retail_price, category_instance_id, label_id, creation_date, last_update_date, last_update_user_id) values (1,1234,'Test Factory Code 1', 'Test Product Code 1', 'Test Product Name 1', 'Test Display Name 1', 101, 'Test Summary 1', 'Test Description 1', 1, 1, 201, 1, current_date(), current_date(), 1)
insert into product_option(id, option_key, option_value, product_id) values(1, 'color', 'black', 1)
insert into product_option(id, option_key, option_value, product_id) values(2, 'gender', 'male', 1)

insert into product(id, factory_barcode, factory_code, product_code, product_name, display_name, gender_instance_id, summary, description, wholesale_price, retail_price, category_instance_id, label_id, creation_date, last_update_date, last_update_user_id) values (2,4321,'Test Factory Code 2', 'Test Product Code 2', 'Test Product Name 2', 'Test Display Name 2', 102, 'Test Summary 2', 'Test Description 2', 1, 1, 202, 1, current_date(), current_date(), 1)
insert into product_option(id, option_key, option_value, product_id) values(3, 'color', 'white', 2)
insert into product_option(id, option_key, option_value, product_id) values(4, 'gender', 'female', 2)
